.github/workflows/ci.yml
Fixes #4 .
- Added ci with github action
=> github action implements

.github/workflows/ci.yml
Fixes #7 .
- add caches both vender/bundle and node_modules
=> #7 github actionにcacheを追加する

doc/er.dot
Fixes #15  .
- added title into bridge_conents
=> added title into bridge_contents

app/views/bridges/show.html.slim
Fixes #18 .
- Added link to inspections from bridges#show
=> #18 added link to inspections from bridge#show

README.md, README_ja.md
=> #36 added README_ja

app/controllers/soundnesses_controller.rb, app/controllers/top_controller.rb, app/models/dashboard.rb, app/views/bridges/show.html.slim, app/views/layouts/user.html.slim, app/views/top/index.html.slim, spec/models/dashboard_spec.rb
Fixes #35 .
- supports dashboard function
- fixes small issues
=> #35 supports dashboard function

app/models/pointcloud.rb
Fixes a bug of #55 .
- fix parameter of pdal translate
=> (refs #55) fixed coordinate system

Capfile, Gemfile, Gemfile.lock, config/deploy.rb, config/deploy/production.rb
WIP #37 .
- Added capistrano for test
=> #37 WIP: added capistrano

app/javascript/stylesheets/common.scss
Fixes #66 .
- delete original css
=> #66 delete original css

doc/er.dot
Fixes #68 .
- updated er diagram
=> #68 updated er diagram

app/controllers/bridge_content_injuries_controller.rb, app/javascript/packs/apps/bridge_content_injury_select.ts, app/javascript/packs/apps/seek.ts, app/javascript/packs/apps/show_bridge_content.ts, app/models/bridge_content_injury.rb, app/views/bridge_content_injuries/_form.html.slim, app/views/bridge_contents/_bridge_content.json.jbuilder, spec/factories/bridge_content_injuries.rb, spec/models/bridge_content_injury_spec.rb, spec/requests/bridge_content_injuries_spec.rb
Fixes #73 .
- enable set seek into bridge_content_injury
=> #73 enable set seek into bridge_content_injury

config/deploy.rb
Fixes #76 .
- set puma worker timeout
=> #76 set puma worker timeout

app/models/bridge_content.rb, app/views/bridge_contents/_bridge_content.json.jbuilder
Fixes #78 .
- break if exif date_time is null
=> #78 break if exif date_time is null

app/controllers/bridge_main_contents_controller.rb, app/controllers/bridges_controller.rb, app/controllers/regular_inspections_controller.rb, app/javascript/packs/apps/regular_inspection_image_list.ts, app/javascript/packs/apps/regular_inspection_main_contents.ts, app/javascript/packs/apps/regular_inspection_tab.ts, app/javascript/packs/commons/image-list.ts, app/javascript/packs/commons/tab.ts, app/javascript/stylesheets/commons/image-list.scss, app/javascript/stylesheets/commons/tab.scss, app/models/bridge.rb, app/views/bridge_contents/index.html.slim, app/views/bridges/_form.html.slim, app/views/bridges/show.html.slim, app/views/regular_inspections/show.html.slim, config/locales/translation_en.yml, config/locales/translation_ja.yml, config/routes.rb, spec/factories/bridges.rb, spec/models/bridge_spec.rb, spec/requests/bridge_main_contents_request_spec.rb, spec/requests/bridges_spec.rb, spec/routing/bridge_main_contents_routing_spec.rb
Fixes #80 .
- add bridge attributes
- add main contents supports
- add tab function
=> #80 add some attribute into bridge

app/javascript/packs/apps/regular_inspection_injury_dialog.ts, app/javascript/stylesheets/commons/dialog.scss, app/views/regular_inspections/show.html.slim, config/locales/translation_en.yml, config/locales/translation_ja.yml
Fixes #83 .
- enable show injury status
=> #83 enable show injury status with dialog

app/controllers/bridges_controller.rb, app/models/bridge.rb, app/views/bridges/_bridge.html.slim, app/views/bridges/_form.html.slim, app/views/bridges/show.html.slim, config/locales/translation_en.yml, config/locales/translation_ja.yml, spec/requests/bridges_spec.rb
Fixes #82 .
- add some attributes into bridge
=> #82 added some attributes into bridge

app/controllers/diagnoses_controller.rb, app/controllers/regular_inspections_controller.rb, app/models/component.rb, app/models/diagnosis.rb, app/views/diagnoses/show.html.slim, spec/models/diagnosis_spec.rb, spec/views/diagnoses/index.html.slim_spec.rb
Fixes #85 .
- added uniqueness to component_category
- remove unselected
- set order for view
- guard if diagnosis.injury is null
=> #85 added uniqueness to component_category

app/controllers/bridge_content_injuries_controller.rb, app/controllers/bridge_contents_controller.rb, app/javascript/packs/apps/show_bridge_content.ts, app/javascript/packs/map/editor/ortho_geojson_editor.ts, app/javascript/packs/map/ortho_image.ts, app/models/bridge_content.rb, app/models/bridge_content_injury.rb, app/views/bridge_content_injuries/_form.html.slim, app/views/bridge_contents/_bridge_content.json.jbuilder, app/views/regular_inspections/show.html.slim
Fixes #45 .
- enable to show ortho in bridge_content_injury
- enable to draw geojson into ortho image
-
=> #45 enable to show ortho in bridge_content_injury

app/controllers/injuries_controller.rb, app/models/injury.rb, app/views/injuries/_form.html.slim, app/views/injuries/index.html.slim, app/views/injuries/show.html.slim, app/views/regular_inspections/show.html.slim, config/locales/translation_en.yml, config/locales/translation_ja.yml, spec/requests/injuries_spec.rb
Fixes #91 .
- added injury content and show it
=> #91 added injury contents and show it

app/javascript/stylesheets/commons/card.scss, app/views/bridges/show.html.slim
Fixes #101 .
- fixes card style
=> #101 fixes card style

app/controllers/components_controller.rb, app/views/bridges/index.html.slim, app/views/components/_form.html.slim, app/views/components/edit.html.slim, app/views/components/index.html.slim, app/views/components/new.html.slim, app/views/components/show.html.slim, app/views/layouts/user.html.slim, config/routes.rb, spec/requests/components_spec.rb, spec/routing/components_routing_spec.rb, spec/views/components/edit.html.slim_spec.rb, spec/views/components/index.html.slim_spec.rb, spec/views/components/new.html.slim_spec.rb, spec/views/components/show.html.slim_spec.rb
Fixes #103 .
- move component to under the bridge
=> #103 move component to under the bridge

app/views/bridge_content_injuries/index.html.slim, app/views/bridge_contents/index.html.slim, app/views/components/index.html.slim, app/views/diagnoses/index.html.slim, app/views/injuries/index.html.slim, app/views/regular_inspections/index.html.slim
Fixes #104 .
- added back buttons
=> #104 added back buttons

app/models/bridge.rb, app/views/bridges/_bridge.html.slim, app/views/bridges/_form.html.slim, config/locales/translation_en.yml, config/locales/translation_ja.yml
Fixes #107 .
- priority to integer
- selectable
=> #107 priority to integer and selectable

app/controllers/top_controller.rb, app/javascript/packs/map/bridges.ts, app/javascript/stylesheets/map/popup.scss, app/views/top/index.html.slim
Fixes #109 .
- added bridge list map in dashboard view
=> #109 added bridge list map in dashboard

app/controllers/top_controller.rb, app/javascript/packs/apps/soundness_chart.ts, app/javascript/packs/commons/colors.ts, app/models/dashboard.rb, app/views/top/index.html.slim, config/locales/translation_en.yml, config/locales/translation_ja.yml, package.json, spec/models/dashboard_spec.rb, yarn.lock
Fixes #110 .
- Show graph sorted by bridge's soundnesses
=> #110 Show graph sorted by bridge's soundnesses

app/models/dashboard.rb
Fixes #115 .
- added nil check
=> #115 added nil check

app/models/dashboard.rb
Fixes #115 .
- fixes 115 again
=> #115 forget += 1

app/controllers/bridges_controller.rb, app/controllers/top_controller.rb, app/javascript/packs/apps/kind_of_bridge_chart.ts, app/models/bridge.rb, app/models/dashboard.rb, app/views/bridges/_bridge.html.slim, app/views/bridges/_form.html.slim, app/views/top/index.html.slim, config/locales/translation_en.yml, config/locales/translation_ja.yml, spec/models/dashboard_spec.rb
Fixes #118 .
- added kind of bridge
- added graph sorted by kind_of_bridge and year_in_service
=> #118 added kind of bridge

app/models/diagnosis.rb, config/locales/translation_en.yml, config/locales/translation_ja.yml, spec/models/diagnosis_spec.rb
Fixes #120 .
- added '4' into diagnosis_results
=> #120 added '4' into diagnosis_results

.github/workflows/ci.yml, README.md, README_ja.md, app/models/game_tile.rb, spec/jobs/game_tile_job_spec.rb
Fixes #125 .
- use vips for background tasks
- fixes README
=> Fixes #125

app/models/game_tile.rb
Fixes #127 .
- use vips dzsave
=> #127 use vips dzsave instead of extract_area

app/models/game_tile.rb
=> fixes max scale

app/javascript/packs/apps/show_bridge_content.ts
Fixes #130 .
- check geojson input field
=> fixes #130: enable to write geojson in ortho view

app/views/commons/_drawer_menu_item.html.slim, app/views/soundnesses/index.html.slim
Fixes #132 .
- added back button into soundness
- force link to list
=> #132 added back button and fixes link
